#!/bin/bash

# read-menu: программа вывода системной информации,
#		управление с помощью менею


clear
echo "
Pleas Select:

1. Display System Info
2. Display Disk Space
3. Display Home Space
0. Quit
"
read -p "Enter selection [0-3] > "

if [[ $REPLAY =~ ^[0-3]$ ]]; then
	if [[ $REPLAY == 0 ]]; then
		echo "Program terminated."
		exit
	fi
	if [[ $REPLAY == 1 ]]; then
		echo "Hostname: $HOSTNAME"
		uptime
		exit
	fi
	if [[ $REPLAY == 2 ]]; then
		df -h
		exit
	fi
	if [[ $REPLAY == 3 ]]; then
		if [[ $(id -u) -eq 0 ]]; then
			echo "Home ($USER)"
			du -sh $HOME
		fi
		exit
	fi
else
	echo "Invalid entry." >&2
	exit 1
fi
